{% set name = "json_tricks" %}
{% set version = "3.13.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9f63f275de0b38ef4a535a8205bef9cbeef9aa509f5df9e661985b7cb18c9b94

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - json_tricks

about:
  home: "https://github.com/mverleg/pyjson_tricks"
  license: BSD
  license_family: BSD
  license_file: 
  summary: "Extra features for Python's JSON: comments, order, numpy, pandas, datetimes, and many more! Simple but customizable."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
