{% set name = "ABR" %}
{% set version = "0.0.3" %}
{% set build = 1 %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: edf4cf9d02a732498f083c5f61d15110568494661968796fe6bc719ae37efd7d
   
build:
  # Increment if this is a new build for the same version
  number: {{ build }}

  entry_points:
    - abr = abr.app:main_launcher
    - abr_gui = abr.app:main_gui
    - abr_batch = abr.app:main_batch

requirements:
  build:
    - python
    - setuptools
  host:
    - python
    - pip
  run:
    - python >=3.6,<3.8
    - enaml >=0.10.4
    - numpy >=1.17.2
    - matplotlib >=3.0.0
    - scipy >=1.3.1
    - pandas >=0.25

test:
  imports:
    - abr
    - abr.app
    - abr.data
    - abr.parsers
    - abr.parsers.PSI
  commands:
    - abr
    - abr_gui --help
    - abr_batch --help

about:
  home: https://github.com/bburan/abr
  license: BSD 3-clause
  license_family: BSD
  summary: GUI application for analyzing ABR waveforms

extra:
  recipe-maintainers:
    - bburan
