{% set name = "psiexperiment" %}
{% set version = "0.1.5rc3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 0ac4c5d1cab578f9437ae8204f72a70272eade69eeb153c5afab40faa483faa4

build:
  noarch: python

  # Increment if this is a new build for the same version.
  number: 1

  entry_points:
    - psi=psi.application.psi_launcher:main
    - psi-config=psi.application:config
    - psi-behavior=psi.application.base_launcher:main_animal
    - psi-calibration=psi.application.base_launcher:main_calibration
    - psi-cfts=psi.application.base_launcher:main_ear
    - psi-cohort=psi.application.base_launcher:main_cohort
    - psi-summarize-abr=psi.data.io.summarize_abr:main
    - psi-summarize-abr-gui=psi.data.io.summarize_abr:main_gui
    - psi-summarize-abr-auto=psi.data.io.summarize_abr:main_auto

  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip

  run:
    # Enaml does not support 3.8 bytecode changes yet
    - python >=3.6,<3.8
    - enaml >=0.10.4
    - numpy >=1.17.2
    - scipy >=1.3.1
    - bcolz >=1.2.1
    - joblib >=0.13.2
    - palettable >=3.3.0
    - pyqtgraph >=0.10.0
    - json_tricks
    - pydaqmx >=1.4.2.post1

test:
  imports:
    - psi
    - psi.application
    - psi.application.experiment
    - psi.context
    - psi.controller
    - psi.controller.calibration
    - psi.controller.devices
    - psi.controller.engines
    - psi.core
    - psi.core.enaml
    - psi.data
    - psi.data.io
    - psi.data.sinks
    - psi.experiment
    - psi.token
  commands:
    - psi-config --help
    - psi-summarize-abr --help
    - psi-summarize-abr-gui --help
    - psi-summarize-abr-auto --help

about:
  home: https://github.com/bburan/psiexperiment
  license: BSD 3-clause
  license_family: BSD
  summary: "Module for running trial-based experiments."
  doc_url: https://psiexperiment.readthedocs.io
  dev_url: https://github.com/bburan/psiexperiment

extra:
  recipe-maintainers:
    - bburan
